### ISSUE TITLE
running the script

### ISSUE THREAD

**Issue by Hunter556** [genie-js/recage#16]
When i try to run the script i get this error:

TypeError: RecordedGame is not a function

**Comment by goto-bus-stop** [comment]
The readme example is a newer version than the npm package. with the version currently on npm, you need to do:

```js
const RecordedGame = require('recage').default
```

That'll be fixed in the next release. The current version on npm is missing a lot of the header information; I'm planning on doing a new release once the header reading is quite robust so you can get more player info and so on out of it.

**Comment by Hunter556** [comment]
the error is gone.
in a side note : how to do I run the script to parse a certain file ? do I send the file path as an argument in the cmd line? Sorry for the noob question, my experience with node js is so limited

**Comment by goto-bus-stop** [comment]
Change it to `RecordedGame(process.argv[2])`. (The 0th argv is the node command, 1st argv is the running file, 2nd and on are additional arguments) you can then do `node script.js rec.mgz`

**Comment by Hunter556** [comment]
It worked, but does it handle all records version? I tried with wk record, and some old aoc record, both gave me something like this :  u15: <Buffer 00 00 00 00 00 00 00> }
events.js:183
      throw er; // Unhandled 'error' event
      ^

**Comment by goto-bus-stop** [comment]
I think it only works with UserPatch 1.4 records right now. WololoKingdoms uses UP 1.5.

**Comment by Hunter556** [comment]
weird,  i tried it with UP 1.4 version but im getting this :Error: EBADF: bad file descriptor, close
